name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64

    steps:
    - name: Checkout the code
      uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Debug
      run: |
        echo ${{ env.DOCKER_TARGET_PLATFORM }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Run Buildx (push image)
      if: success()
      run: |        
        docker buildx build \
        --platform ${{ env.DOCKER_TARGET_PLATFORM }} \
        --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA \
        --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest \
        --file ./Dockerfile \
        --output type=image,push=true .